### ISSUE TITLE
Kbase models, and ModelSEED pool construction

### ISSUE THREAD

**Issue by hellopeccat** [canc1993/cheshire-gapfilling#8]
Hi.

I would like to learn about the possibility to run CHESHIRE with xml models reconstructed from Kbase. 
It is known that Kbase provides ModelSEED-based pipelines for construction, but I am not completely sure about whether Kbase models generated from those pipelines are also available for CHESHIRE. 

First of all, due to lack of preparing ModelSEED pool in advance, I run CHESHIRE with a Kbase model using BiGG pool to check out whether this model is readable as input. Subsequently, I succeeded to get the output of predicted_scores and similarity_scores, though all the scores are wrongly calculated to the same value. 
(Kbase models are generally curated as follows:
![Kbase-model-in-xml](https://github.com/user-attachments/assets/57979c51-ab2e-4ed0-a5d5-ee9c024dbd6b)
If any exemplified xml file is required, please feel it free to let me see.)

Another concerned question is how to build a ModelSEED pool. 
I find it infeasible to directly get a xml pool from ModelSEED ontology, since ModelSEED provides a tsv file for universal reactions in Github but only accepts fasta file to generate xml files in its home website https://modelseed.org/. 
However, if using third-party ModelSEED-based platforms, the pools generated by them will encounter a similar concern to the models generated by Kbase.   

To my current knowledge, the key point of these questions is about namespace, while I have no idea of the namespaces adopted by ModelSEED. Previously, I failed to seek out a documentation in ModelSEED to show its namespaces.   

Is there any suggestion to construct ModelSEED pools? After this job to be addressed, I can thereby review the the possibility to run CHESHIRE with Kbase models by myself.

**Comment by canc1993** [comment]
Hello, You can map the reaction identifiers between BiGG and ModelSEED. The mapping files can be downloaded from the BiGG database.

**Comment by hellopeccat** [comment]
Hi @canc1993,

Pretty glad to receive your rapid reply, and I will consider the potential solution in accordance with your advice soon.

Currently, I am trying to build a Kbase universe pool, since the Kbase models(built by ModelSEED-based pipelines) are readable for CHESHIRE. By this way, I would like to see whether Kbase models will successfully match Kbase universe pool.
This work has partially been done, and I am going to address some mistakes as follows:
![image](https://github.com/user-attachments/assets/9ae4c411-3c15-4565-8c0c-35ac167249fc)

I do thank you for your kind advice sincerely, and I suppose it makes sence. Ummm..., but frankly speaking, I still have no idea about how to create xml files in the downstream of your suggested solution.
For instance, I can do the mapping job, but after that I have to comply with the namespaces of ModelSEED (which is consistent with ModelSEED models, right?). I am not familiar with the curation of xml files. That is an important reason for me to try to finish this work using existing automatic or semi-automatic pipelines like Kbase or CarveMe, rather than by manual effort.

**Comment by hellopeccat** [comment]
Hi @canc1993,
I have virtually succeed in calculating confidence scores with a Kbase model and a Kbase universe pool. I feel so delighted to share this nice message with you. 

**Kbase models are available to be gapfilled using CHESHIRE. Spectacular!** 

Though the pool construction process indeed took more efforts than I previously imagined, **the results below exactly indicated that it finally worked.**(The "null" cells have valid values in other rows, which are generated from the original BiGG test. What a careless mistake~)
 ![image](https://github.com/user-attachments/assets/eb79c507-749d-4839-8bc6-da493ba7f114)

Next stage, I will try to refine my current Kbase pool (including 44370 reactions) which results in totally 4300+ candidate reactions (confidence score >0.9995) before filtered by similarity scores. That is too universal. My preliminary plan is as follows:

  1. dereplicate reactions with ambiguous equilibrium and linked to any other reactions with smaller ids. 
  2. discard biomass, exchange, demand and sink reactions in accordance with your work.
  3. delete reactions without a compartment of cytosol or extracellular.  
  4. delete reactions solely from plant or fungus models. 

Looking forward to what will happen to the size of final candidate reactions after pool refinement and filtration with similarity scores.

**Comment by canc1993** [comment]
Thank you for the updates. Pool refinement is important. We didn't do it in our paper, but it's worth investigating.

Best, Can

**Comment by xztJLAU** [comment]
Hi,

I’m interested in how you utilized the JSON or TSV files from ModelSEED to construct a universe pool. Did you use any specific tools or scripts for this process? If so, could you share some details?

**Comment by hellopeccat** [comment]
> Hi,
> 
> I’m interested in how you utilized the JSON or TSV files from ModelSEED to construct a universe pool. Did you use any specific tools or scripts for this process? If so, could you share some details?

Hi @xztJLAU ,

Download the tsv files of compounds and reactions, subsequently integrating them into a xlsx file, the format of which you could refer that of a normal genome-based metabolic model produced by the Kbase. 

Just perceive the universe pool as a model of a single super-organism, and everything of the construction process is the same. You can upload this xlsx file of universe pool as a model to the Kbase platform, trim it carefully and then transform it on the web-server to the format CHESHIRE desired.  

We don't need to compile a ModelSEED's xml file by script, just utilize Kbase to finish it. That is convenient enough.

Best, peccat.

**Comment by xztJLAU** [comment]
Hi,
Thanks for the suggestion,,kbased is  convenient enough.  I'm also getting the same error as you, maybe I should fill in all the blanks as Unknow,the error log:RuntimeError: The size of tensor a (40190) must match the size of tensor b (36437) at non-singleton dimension 0

Best,xztJLAU

**Comment by xztJLAU** [comment]
> Hi, Thanks for the suggestion,,kbased is convenient enough. I'm also getting the same error as you, maybe I should fill in all the blanks as Unknow,the error log:RuntimeError: The size of tensor a (40190) must match the size of tensor b (36437) at non-singleton dimension 0
> 
> Best,xztJLAU

A small mistake, it seems that only the reaction represented by the S-matrix and the non-0 column in the S-matrix needs to be removed, so that the overside is not null

**Comment by hellopeccat** [comment]
Hi @xztJLAU,

I don't think a big difference between tensor a and b is reasonable. As you see, when I encountered this sort of bug, there was only a small one of 15, which I perceive is resulted from the indices of some reactions missing from the argument `batch` in CHESHIRE.py . At that time, I adjust the original function `norm_pool`:

```
def norm_pool(x, batch):
        print("x size:", x.size())
        print("batch size:", batch.size(), "batch max:", batch.max().item(), "batch min:", batch.min().item())
        size = int(batch.max().item() + 1)
        counts = scatter(torch.ones_like(batch), batch, dim=0, dim_size=size, reduce='sum')
        print("counts size:", counts.size())
        squared_x = x ** 2
        scattered = scatter(squared_x, batch, dim=0, dim_size=size, reduce='sum')
        print("scattered size:", scattered.size())
        assert scattered.size(0) == counts.size(0), "Sizes do not match."
        y_norm = torch.sqrt(scattered / counts.view(-1, 1))
        print("y_norm size:", y_norm.size())
        return y_norm
```

This will ensure the norm pool produces a correct count of actual number of all the input reactions. However, I am not sure about its impact on the downstream prediction. Since only 15 reactions differ in my case, I believe the impact can be ignored. 

However, a big difference resulted from missing indices may be unrealistic, and indicate manual mistakes of curating the reactions. If your pool has 40190 reactions, the correct tensor shall also return 40190, and thousands of reactions were wrongly identified by CHESHIRE in your case.

**Comment by xztJLAU** [comment]
Thanks for the code, like I said above, I removed all reactions with a metric factor of 0 so that the tensor dimension would not report an error
